# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/perturbative-transformer-cognition',
                'doc_host': 'https://oelmiedany.github.io',
                'git_url': 'https://github.com/oelmiedany/perturbative-transformer-cognition',
                'lib_path': 'perturbative_transformer_cognition'},
  'syms': { 'perturbative_transformer_cognition.core': { 'perturbative_transformer_cognition.core.foo': ( 'core.html#foo',
                                                                                                          'perturbative_transformer_cognition/core.py')}}}
