# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/perturbative-llm-cognition',
                'doc_host': 'https://oelmiedany.github.io',
                'git_url': 'https://github.com/oelmiedany/perturbative-llm-cognition',
                'lib_path': 'perturbative_llm_cognition'},
  'syms': { 'perturbative_llm_cognition.core': { 'perturbative_llm_cognition.core.conversation_loop': ( 'core.html#conversation_loop',
                                                                                                        'perturbative_llm_cognition/core.py'),
                                                 'perturbative_llm_cognition.core.load_model': ( 'core.html#load_model',
                                                                                                 'perturbative_llm_cognition/core.py'),
                                                 'perturbative_llm_cognition.core.run_model': ( 'core.html#run_model',
                                                                                                'perturbative_llm_cognition/core.py')}}}
